#!/usr/bin/env python3
"""Turn the vendored Spark grammar into a Databricks grammar for Python.

Two jobs, in this order.

**1. Retarget Java to Python.** Spark writes its grammar for the Java target:
`@members` blocks and inline actions are Java source, which ANTLR copies
verbatim into whatever it generates. Under the Python target that produces a
file which will not import. We delete those blocks (ported to Python in
dbsqlparse.antlr_base and attached via `superClass`) and rewrite every inline
action and semantic predicate.

**2. Add the Databricks surface.** Databricks SQL is a superset of Spark SQL.
Everything the two share comes from the vendored grammar; the Databricks-only
syntax -- Delta operations, Unity Catalog DDL, QUALIFY, path relations -- lives
in grammar/extensions/ and is injected here. Injecting rather than hand-editing
is what lets us re-vendor a newer Spark without losing the extensions.

Both jobs fail loudly rather than silently. Java rewrites are exact-string
substitutions with expected occurrence counts, and extension injection uses
the marker comments Spark maintains in its own grammar as anchors. When Spark
moves something, this script stops with a specific message naming what moved,
instead of emitting a parser that cannot be imported or, worse, one that
imports and is quietly missing rules.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
VENDOR_DIR = REPO_ROOT / "grammar" / "vendor"
OUT_DIR = REPO_ROOT / "grammar" / "databricks"

BASE_MODULE = "dbsqlparse.antlr_base"

# (java source, python replacement, expected count) -- see module docstring.
LEXER_ACTIONS = [
    ("{incComplexTypeLevelCounter();}", "{self.incComplexTypeLevelCounter()}", 3),
    ("{decComplexTypeLevelCounter();}", "{self.decComplexTypeLevelCounter()}", 1),
    ("{markUnclosedComment();}", "{self.markUnclosedComment()}", 1),
    ("{isShiftRightOperator()}?", "{self.isShiftRightOperator()}?", 2),
    ("{isValidDecimal()}?", "{self.isValidDecimal()}?", 5),
    ("{!isHint()}?", "{not self.isHint()}?", 1),
]

PARSER_ACTIONS = [
    ("{!legacy_setops_precedence_enabled}?", "{not self.legacy_setops_precedence_enabled}?", 2),
    ("{legacy_setops_precedence_enabled}?", "{self.legacy_setops_precedence_enabled}?", 1),
    ("{!SQL_standard_keyword_behavior}?", "{not self.SQL_standard_keyword_behavior}?", 2),
    ("{SQL_standard_keyword_behavior}?", "{self.SQL_standard_keyword_behavior}?", 1),
    ("{!double_quoted_identifiers}?", "{not self.double_quoted_identifiers}?", 1),
    ("{double_quoted_identifiers}?", "{self.double_quoted_identifiers}?", 1),
    (
        "{!legacy_exponent_literal_as_decimal_enabled}?",
        "{not self.legacy_exponent_literal_as_decimal_enabled}?",
        2,
    ),
    (
        "{legacy_exponent_literal_as_decimal_enabled}?",
        "{self.legacy_exponent_literal_as_decimal_enabled}?",
        1,
    ),
]

BANNER = (
    "// GENERATED by scripts/patch_grammar.py from grammar/vendor/{src} -- do not edit.\n"
    "// Java actions rewritten for the ANTLR Python target; @members ported to\n"
    "// {base}.{cls}, attached via superClass.\n"
)


class PatchError(RuntimeError):
    pass


def strip_members_block(text: str, grammar: str) -> str:
    """Remove the `@members { ... }` block, matching braces properly."""
    start = text.find("@members")
    if start == -1:
        raise PatchError(f"{grammar}: no @members block found -- has the grammar changed shape?")
    open_brace = text.find("{", start)
    if open_brace == -1:
        raise PatchError(f"{grammar}: @members with no opening brace")

    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                if "@members" in text[i:]:
                    raise PatchError(f"{grammar}: more than one @members block; only one is handled")
                return text[:start] + text[i + 1 :].lstrip("\n")
    raise PatchError(f"{grammar}: unbalanced braces in @members block")


def apply_actions(text: str, actions, grammar: str) -> str:
    for java, python, expected in actions:
        found = text.count(java)
        if found != expected:
            raise PatchError(
                f"{grammar}: expected {expected} occurrence(s) of {java!r}, found {found}. "
                f"The vendored grammar has changed -- update the mapping table in "
                f"scripts/patch_grammar.py before regenerating."
            )
        text = text.replace(java, python)
    return text


# Matches an action or predicate block, but not a Unicode property escape such
# as [\p{L}] or [\p{Alnum}], which legitimately contains braces.
ACTION_RE = re.compile(r"(?<!\\p)\{[^{}]*\}\??")


OPTIONS_RE = re.compile(r"options\s*\{[^{}]*\}")


def assert_no_java_left(text: str, grammar: str) -> None:
    """Fail if any action block survived the rewrite still looking like Java."""
    # An `options { tokenVocab = ...; }` block is grammar config, not an action.
    scannable = OPTIONS_RE.sub("", text)
    leftovers = []
    for match in ACTION_RE.finditer(scannable):
        body = match.group(0)
        if "\\p{" in body:
            continue
        inner = body.strip("{}?").strip()
        if not inner:
            continue
        # Every action we emit calls through the Python base class.
        if "self." not in inner:
            leftovers.append(body)
    if leftovers:
        raise PatchError(
            f"{grammar}: {len(leftovers)} action(s) were not rewritten to Python: "
            f"{sorted(set(leftovers))[:5]}. Add them to the mapping table in "
            f"scripts/patch_grammar.py."
        )


# --------------------------------------------------------------------------
# Databricks extensions
#
# Databricks SQL is a superset of Spark SQL. Everything the two share comes
# from the vendored grammar; the Databricks-only surface lives in
# grammar/extensions/ and is injected here rather than hand-edited into the
# generated output, so re-vendoring a newer Spark keeps the extensions.
#
# Anchors are the marker comments Spark maintains in its own grammar, which
# are far more stable than line numbers or surrounding rule text.
# --------------------------------------------------------------------------

EXT_DIR = REPO_ROOT / "grammar" / "extensions"

LEXER_KEYWORD_ANCHOR = "//--SPARK-KEYWORD-LIST-END"
ANSI_NON_RESERVED_ANCHOR = "//--ANSI-NON-RESERVED-END"
DEFAULT_NON_RESERVED_ANCHOR = "//--DEFAULT-NON-RESERVED-END"
# The last alternative of the `statement` rule; ours go in ahead of it so the
# catch-all stays last.
STATEMENT_ANCHOR = "    | unsupportedHiveNativeCommands .*?                                #failNativeCommand"


def read_keywords() -> list[str]:
    """Load the new-keyword list, ignoring comments and blank lines."""
    path = EXT_DIR / "keywords.txt"
    if not path.exists():
        raise PatchError(f"missing {path}")
    words = []
    for line in path.read_text().splitlines():
        line = line.split("#", 1)[0].strip()
        if line:
            words.append(line)
    if len(words) != len(set(words)):
        dupes = sorted({w for w in words if words.count(w) > 1})
        raise PatchError(f"duplicate keywords in keywords.txt: {dupes}")
    return words


def read_fragment(name: str) -> str:
    path = EXT_DIR / name
    if not path.exists():
        raise PatchError(f"missing {path}")
    return path.read_text()


def insert_before(text: str, anchor: str, addition: str, grammar: str) -> str:
    if anchor not in text:
        raise PatchError(
            f"{grammar}: anchor {anchor!r} not found. Spark moved or renamed it; "
            f"update the anchors in scripts/patch_grammar.py."
        )
    return text.replace(anchor, addition + anchor, 1)


# Keywords that open a complex type and so must drive the lexer's depth
# counter, exactly as Spark's own ARRAY/MAP/STRUCT do. Without the action,
# the closing `>>` of `OBJECT<a: MAP<STRING, INT>>` lexes as a shift-right
# operator and the type fails to parse.
COMPLEX_TYPE_ACTIONS = {"OBJECT": "{self.incComplexTypeLevelCounter()}"}


def add_lexer_keywords(text: str, keywords: list[str]) -> str:
    """Define each new keyword as a token, ahead of the IDENTIFIER rule."""
    already = [k for k in keywords if re.search(rf"^{k}\s*:", text, re.M)]
    if already:
        raise PatchError(
            f"SqlBaseLexer.g4: these keywords are now defined by Spark itself: "
            f"{already}. Remove them from grammar/extensions/keywords.txt."
        )
    unknown = set(COMPLEX_TYPE_ACTIONS) - set(keywords)
    if unknown:
        raise PatchError(
            f"COMPLEX_TYPE_ACTIONS names {sorted(unknown)}, which are not in "
            f"grammar/extensions/keywords.txt."
        )
    block = ["", "// --- Databricks extensions (see grammar/extensions/keywords.txt) ---"]
    for kw in keywords:
        action = COMPLEX_TYPE_ACTIONS.get(kw)
        block.append(f"{kw}: '{kw}' {action};" if action else f"{kw}: '{kw}';")
    block += [""]
    return insert_before(text, LEXER_KEYWORD_ANCHOR, "\n".join(block) + "\n", "SqlBaseLexer.g4")


def add_non_reserved(text: str, keywords: list[str]) -> str:
    """Keep every new keyword usable as an identifier.

    Defining a lexer token stops that word matching IDENTIFIER. Without this,
    a column named `tag` or `pattern` would become a syntax error -- a recall
    regression that blocks good SQL. Databricks treats these as non-reserved
    too, so this matches its behaviour as well as protecting recall.
    """
    block = "\n".join(
        ["", "// --- Databricks extensions ---"] + [f"    | {kw}" for kw in keywords] + [""]
    )
    text = insert_before(text, ANSI_NON_RESERVED_ANCHOR, block + "\n", "SqlBaseParser.g4")
    text = insert_before(text, DEFAULT_NON_RESERVED_ANCHOR, block + "\n", "SqlBaseParser.g4")
    return text


def add_statements(text: str) -> str:
    fragment = read_fragment("statements.g4frag")
    return insert_before(text, STATEMENT_ANCHOR, fragment.rstrip("\n") + "\n", "SqlBaseParser.g4")


def add_qualify_clause(text: str) -> str:
    """Thread QUALIFY into the select statement, between HAVING and WINDOW."""
    anchor = (
        "      havingClause?\n"
        "      windowClause?                                                         "
        "#regularQuerySpecification"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find regularQuerySpecification to add "
            "QUALIFY to; the query rules have changed shape."
        )
    replacement = (
        "      havingClause?\n"
        "      qualifyClause?\n"
        "      windowClause?                                                         "
        "#regularQuerySpecification"
    )
    return text.replace(anchor, replacement, 1)


def add_path_relation(text: str) -> str:
    """Allow a bare path literal where a table is expected.

    Databricks reads files directly by path, most visibly inside COPY INTO:

        COPY INTO t FROM (SELECT a::bigint FROM '/vol/landing') FILEFORMAT = PARQUET

    Spark's relationPrimary has no alternative for a string literal, so the
    inner query fails to parse. Adding it here makes the parser accept path
    relations anywhere a table can appear. That is broader than strictly
    necessary, and deliberately so: over-accepting costs a missed error, while
    under-accepting blocks a merge request that was fine.
    """
    anchor = (
        "relationPrimary\n"
        "    : identifierReference temporalClause?\n"
        "      optionsClause? sample? tableAlias                     #tableName"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find relationPrimary to add path "
            "relations to; the relation rules have changed shape."
        )
    addition = (
        "\n    | path=stringLit temporalClause?\n"
        "      optionsClause? sample? tableAlias                     #pathRelation"
    )
    return text.replace(anchor, anchor + addition, 1)


def add_stream_relation(text: str) -> str:
    """Allow `STREAM` in front of a relation.

    Declarative pipelines read a streaming source by prefixing the relation:

        SELECT * FROM STREAM read_files('/vol/landing', format => 'json')
        SELECT * FROM STREAM orders_bronze

    Spark has no STREAM, so without this the word lexes as an identifier and
    `STREAM read_files(...)` parses as a table named STREAM aliased to
    `read_files`, at which point the argument list is read as a column alias
    list and the first string argument fails. The error therefore lands on the
    path, several tokens away from the real cause -- which is what made this
    look like a string-literal bug rather than a missing keyword.

    Both alternatives are spelled out rather than wrapping relationPrimary,
    so `STREAM` cannot stack on itself or on an inline table.
    """
    anchor = (
        "relationPrimary\n"
        "    : identifierReference temporalClause?\n"
        "      optionsClause? sample? tableAlias                     #tableName"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find relationPrimary to add STREAM "
            "relations to; the relation rules have changed shape."
        )
    addition = (
        "\n    | STREAM identifierReference temporalClause?\n"
        "      optionsClause? sample? tableAlias                     #streamTableName"
        "\n    | STREAM functionTable                                  "
        "#streamTableValuedFunction"
    )
    return text.replace(anchor, anchor + addition, 1)


def add_column_constraints(text: str) -> str:
    """Allow constraints and DLT expectations inside a column list.

    Spark's colDefinitionList holds column definitions only, so every one of
    these is a syntax error against the vendored grammar:

        CREATE TABLE t (k BIGINT NOT NULL PRIMARY KEY)
        CREATE TABLE t (k BIGINT, CONSTRAINT pk PRIMARY KEY (k))
        CREATE OR REFRESH STREAMING TABLE t
            (CONSTRAINT valid EXPECT (id IS NOT NULL) ON VIOLATION DROP ROW)

    The first two are ordinary Databricks DDL; the third is how a declarative
    pipeline states a data-quality expectation. They share a shape -- an entry
    in the column list that is not a column -- so one widening covers all
    three. colDefinitionItem and the rules it needs are appended from
    grammar/extensions/rules.g4frag.
    """
    anchor = (
        "colDefinitionList\n"
        "    : colDefinition (COMMA colDefinition)*\n"
        "    ;"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find colDefinitionList to add "
            "constraints to; the column definition rules have changed shape."
        )
    replacement = (
        "colDefinitionList\n"
        "    : colDefinitionItem (COMMA colDefinitionItem)*\n"
        "    ;"
    )
    return text.replace(anchor, replacement, 1)


def add_inline_column_constraints(text: str) -> str:
    """Allow PRIMARY KEY / REFERENCES directly on a column definition.

    Databricks declares a key on the column rather than as a separate entry:

        key BIGINT NOT NULL PRIMARY KEY
        customer_key BIGINT NOT NULL FOREIGN KEY REFERENCES customers_dim
        order_date_key BIGINT CONSTRAINT order_date_fk
            FOREIGN KEY REFERENCES date_dim

    Spark's colDefinitionOption has no alternative for any of them. The
    CONSTRAINT name is optional here and required in tableLevelConstraint,
    which is what keeps the two apart: an entry starting with CONSTRAINT is a
    table-level constraint, and one starting with an identifier and a type is a
    column that may carry a named key.
    """
    anchor = (
        "colDefinitionOption\n"
        "    : errorCapturingNot NULL\n"
        "    | defaultExpression\n"
        "    | generationExpression\n"
        "    | commentSpec\n"
        "    ;"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find colDefinitionOption to add "
            "inline constraints to; the column definition rules have changed."
        )
    replacement = (
        "colDefinitionOption\n"
        "    : errorCapturingNot NULL\n"
        "    | defaultExpression\n"
        "    | generationExpression\n"
        "    | commentSpec\n"
        "    | (CONSTRAINT constraintName=errorCapturingIdentifier)?\n"
        "        PRIMARY KEY (RELY | NORELY)?\n"
        "    | (CONSTRAINT constraintName=errorCapturingIdentifier)?\n"
        "        FOREIGN? KEY? REFERENCES identifierReference\n"
        "        (LEFT_PAREN multipartIdentifierList RIGHT_PAREN)?\n"
        "        (RELY | NORELY)?\n"
        "    ;"
    )
    return text.replace(anchor, replacement, 1)


def add_at_sign_token(text: str) -> str:
    """Define `@` as a real token so `tbl@v3` can be parsed.

    Spark has no `@`. It falls through to the UNRECOGNIZED catch-all at the
    bottom of the lexer, which exists so statement splitting can skip over text
    it cannot read -- so `SELECT * FROM cdf_demo@v0` cannot parse at all.

    This goes in at the keyword-list anchor, which sits ahead of
    STRING_LITERAL, IDENTIFIER and UNRECOGNIZED, so the new token wins over the
    catch-all while an `@` inside a string literal or a backquoted identifier
    still belongs to that token by longest match. That matters: the corpus is
    full of paths and email addresses like `/Repos/jacek@japila`, and none of
    them may start lexing differently.

    It cannot go through keywords.txt, which generates `NAME: 'NAME';` -- here
    the token name and the literal differ.
    """
    return insert_before(
        text,
        LEXER_KEYWORD_ANCHOR,
        "\n// --- Databricks time travel (see scripts/patch_grammar.py) ---\n"
        "AT_SIGN: '@';\n\n",
        "SqlBaseLexer.g4",
    )


def add_at_version_travel(text: str) -> str:
    """Add the `@version` spelling of time travel.

    Databricks accepts a short form next to the VERSION AS OF that Spark
    already has:

        SELECT * FROM cdf_demo@v0
        SELECT count(*) FROM delta.`/mnt/p`@v524

    Extending temporalClause rather than relationPrimary picks up every place a
    relation can carry one -- plain tables, path relations and STREAM sources --
    from a single alternative.

    `version` is INTEGER_VALUE | stringLit, and `v0` is neither: it lexes as one
    IDENTIFIER. So the alternative accepts an identifier too, which
    over-accepts a little. That is the same trade add_path_relation makes:
    over-accepting costs a missed error, under-accepting blocks a merge request
    that was fine.
    """
    anchor = (
        "temporalClause\n"
        "    : FOR? (SYSTEM_VERSION | VERSION) AS OF version\n"
        "    | FOR? (SYSTEM_TIME | TIMESTAMP) AS OF timestamp=valueExpression\n"
        "    ;"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find temporalClause to add @version "
            "time travel to; the time-travel rules have changed shape."
        )
    replacement = anchor[:-1] + "    | AT_SIGN (version | identifier)\n    ;"
    return text.replace(anchor, replacement, 1)


def add_column_tags(text: str) -> str:
    """Allow tags to be set on a column, not just on the table.

        ALTER TABLE t ALTER COLUMN c SET TAGS ('pii' = 'true')
        ALTER TABLE t ALTER COLUMN c UNSET TAGS ('pii')

    The table-level forms are already extensions (#setTags / #unsetTags); this
    is the column-level counterpart, which hangs off Spark's alterColumnAction.
    """
    anchor = (
        "alterColumnAction\n"
        "    : TYPE dataType\n"
        "    | commentSpec\n"
        "    | colPosition\n"
        "    | setOrDrop=(SET | DROP) errorCapturingNot NULL\n"
        "    | SET defaultExpression\n"
        "    | dropDefault=DROP DEFAULT\n"
        "    ;"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find alterColumnAction to add column "
            "tags to; the ALTER COLUMN rules have changed shape."
        )
    replacement = anchor[:-1] + (
        "    | SET TAGS propertyList\n"
        "    | UNSET TAGS propertyList\n"
        "    ;"
    )
    return text.replace(anchor, replacement, 1)


def add_describe_relation(text: str) -> str:
    """Allow `(DESCRIBE HISTORY t)` where a relation is expected.

        SELECT * FROM (DESCRIBE HISTORY my_students)
        SELECT max(version) FROM (DESCRIBE HISTORY my_streaming_table)

    Spark's aliasedQuery takes a `query`, and DESCRIBE HISTORY is a statement
    rather than a query, so the parenthesised form fails.

    Deliberately narrow: DESCRIBE HISTORY specifically, not `statement`. The
    general form would accept `SELECT * FROM (DROP TABLE x)`, which is the kind
    of over-acceptance that costs a real error rather than a hypothetical one.
    """
    anchor = (
        "relationPrimary\n"
        "    : identifierReference temporalClause?\n"
        "      optionsClause? sample? tableAlias                     #tableName"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find relationPrimary to add DESCRIBE "
            "HISTORY relations to; the relation rules have changed shape."
        )
    addition = (
        "\n    | LEFT_PAREN DESCRIBE HISTORY identifierReference RIGHT_PAREN\n"
        "      tableAlias                                            #describeHistoryRelation"
    )
    return text.replace(anchor, anchor + addition, 1)


def add_managed_location(text: str) -> str:
    """Add Unity Catalog's MANAGED LOCATION to CREATE SCHEMA.

        CREATE SCHEMA s MANAGED LOCATION 's3://bucket/prefix'

    It sets the storage root for managed tables in that schema. The CREATE
    CATALOG counterpart is ours already, in grammar/extensions/statements.g4frag;
    this one has to be spliced because CREATE SCHEMA is Spark's rule.
    """
    anchor = (
        "    | CREATE namespace (IF errorCapturingNot EXISTS)? identifierReference\n"
        "        (commentSpec |\n"
        "         locationSpec |\n"
        "         (WITH (DBPROPERTIES | PROPERTIES) propertyList))*             #createNamespace"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find createNamespace to add MANAGED "
            "LOCATION to; the namespace rules have changed shape."
        )
    replacement = (
        "    | CREATE namespace (IF errorCapturingNot EXISTS)? identifierReference\n"
        "        (commentSpec |\n"
        "         locationSpec |\n"
        "         (MANAGED LOCATION managedLocation=stringLit) |\n"
        "         (WITH (DBPROPERTIES | PROPERTIES) propertyList))*             #createNamespace"
    )
    return text.replace(anchor, replacement, 1)


def add_variant_path(text: str) -> str:
    """Add `v:field` variant extraction to the expression grammar.

    Databricks reads semi-structured VARIANT columns with a colon path:

        SELECT payload:user.id::string, payload:['odd key'] FROM events

    The alternative goes next to #dereference so it sits at the same
    precedence as `.field` access, which is what it is the VARIANT analogue of.
    `::` casts still bind afterwards because castByColon is listed earlier in
    the left-recursive rule.
    """
    anchor = (
        "    | base=primaryExpression DOT fieldName=identifier"
        "                                          #dereference"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find the #dereference alternative to "
            "add VARIANT path extraction next to."
        )
    addition = (
        "\n    | base=primaryExpression COLON path=variantPath"
        "                                    #variantExtract"
    )
    return text.replace(anchor, anchor + addition, 1)


def add_object_data_type(text: str) -> str:
    """Add Databricks' OBJECT<field: TYPE, ...> to the type grammar."""
    anchor = "    | complex=STRUCT (LT complexColTypeList? GT | NEQ)          #complexDataType"
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find the STRUCT dataType alternative "
            "to add OBJECT next to."
        )
    addition = (
        "\n    | complex=OBJECT LT complexColTypeList? GT"
        "                   #complexDataType"
    )
    return text.replace(anchor, anchor + addition, 1)


def add_cluster_by_auto(text: str) -> str:
    """Allow `CLUSTER BY AUTO`, Databricks' automatic liquid clustering.

    Spark's clusterBySpec only takes an explicit column list.
    """
    anchor = (
        "clusterBySpec\n"
        "    : CLUSTER BY LEFT_PAREN multipartIdentifierList RIGHT_PAREN\n"
        "    ;"
    )
    if anchor not in text:
        raise PatchError(
            "SqlBaseParser.g4: could not find clusterBySpec to add CLUSTER BY AUTO to."
        )
    replacement = (
        "clusterBySpec\n"
        "    : CLUSTER BY LEFT_PAREN multipartIdentifierList RIGHT_PAREN\n"
        "    | CLUSTER BY AUTO\n"
        "    ;"
    )
    return text.replace(anchor, replacement, 1)


def add_rules(text: str) -> str:
    return text.rstrip("\n") + "\n\n" + read_fragment("rules.g4frag")


def patch_lexer(text: str) -> str:
    text = strip_members_block(text, "SqlBaseLexer.g4")
    text = apply_actions(text, LEXER_ACTIONS, "SqlBaseLexer.g4")
    assert_no_java_left(text, "SqlBaseLexer.g4")
    text = add_lexer_keywords(text, read_keywords())
    text = add_at_sign_token(text)

    decl = "lexer grammar SqlBaseLexer;"
    if decl not in text:
        raise PatchError("SqlBaseLexer.g4: grammar declaration not found")
    # No @header import here: the ANTLR Python target emits its own
    # `from .SqlBaseLexerBase import SqlBaseLexerBase` for a superClass, and
    # that relative import shadows anything we add. We satisfy it with a shim
    # module in the generated package instead.
    injected = f"{decl}\n\noptions {{ superClass = SqlBaseLexerBase; }}\n"
    text = text.replace(decl, injected, 1)
    return BANNER.format(src="SqlBaseLexer.g4", base=BASE_MODULE, cls="SqlBaseLexerBase") + text


def patch_parser(text: str) -> str:
    text = strip_members_block(text, "SqlBaseParser.g4")
    text = apply_actions(text, PARSER_ACTIONS, "SqlBaseParser.g4")
    assert_no_java_left(text, "SqlBaseParser.g4")

    # Order matters: statements and QUALIFY patch existing rules, so they run
    # while the anchors are still intact; new rules are appended last.
    text = add_non_reserved(text, read_keywords())
    text = add_statements(text)
    text = add_qualify_clause(text)
    text = add_path_relation(text)
    text = add_stream_relation(text)
    text = add_column_constraints(text)
    text = add_inline_column_constraints(text)
    text = add_at_version_travel(text)
    text = add_column_tags(text)
    text = add_describe_relation(text)
    text = add_managed_location(text)
    text = add_cluster_by_auto(text)
    text = add_variant_path(text)
    text = add_object_data_type(text)
    text = add_rules(text)

    opts = "options { tokenVocab = SqlBaseLexer; }"
    if opts not in text:
        raise PatchError("SqlBaseParser.g4: expected options block not found")
    injected = "options { tokenVocab = SqlBaseLexer; superClass = SqlBaseParserBase; }\n"
    text = text.replace(opts, injected, 1)
    return BANNER.format(src="SqlBaseParser.g4", base=BASE_MODULE, cls="SqlBaseParserBase") + text


def main() -> int:
    argparse.ArgumentParser(description=__doc__).parse_args()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    jobs = [
        ("SqlBaseLexer.g4", patch_lexer),
        ("SqlBaseParser.g4", patch_parser),
    ]
    for name, fn in jobs:
        src = VENDOR_DIR / name
        if not src.exists():
            print(f"error: {src} missing -- run scripts/fetch_grammar.py first", file=sys.stderr)
            return 1
        try:
            patched = fn(src.read_text())
        except PatchError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
        dest = OUT_DIR / name
        dest.write_text(patched)
        print(f"patched {name} -> {dest.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
